# Generated by Django 6.1.1 on 2026-09-14 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('short_description', models.TextField()),
                ('overview', models.TextField()),
                ('seo_title', models.CharField(max_length=200)),
                ('seo_description', models.TextField()),
                ('conditions', models.JSONField(default=list)),
                ('treatments', models.JSONField(default=list)),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('image_alt', models.CharField(blank=True, max_length=255)),
                ('featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['ordering', 'id'],
            },
        ),
    ]
